CREATE TABLE CLIENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

CREATE TABLE PRODUCT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    PRICE NUMERIC (20,2)
);

CREATE TABLE PURCHASE_ORDER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENT (ID),
    ORDER_DATE TIMESTAMP,
    TOTAL NUMERIC (20,2)
);

CREATE TABLE PURCHASE_ORDER_ITEM (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PURCHASE_ORDER_ID INTEGER REFERENCES PURCHASE_ORDER (ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
    AMOUNT INTEGER
);
purchase_order_item